### PR TITLE
Rename interation.svg to interaction.svg

### PR DESCRIPTION
**Pull request by vvenv**
typo

### CODE REVIEW

**Comment by yesmeck** [comment]
Thanks for your contribution, rename the icon name would lead to a breaking change, I'll fix it in after https://github.com/ant-design/ant-design/pull/12888

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/488f5a101d8460b7a689c3f2526ae2cba7af8d6f

**Comment by afc163** [comment]
@yesmeck @zombieJ we should merge it and release a patch to fix https://github.com/ant-design/ant-design/issues/13007

**Comment by zombieJ** [comment]
都发到 minor 版本吧，免得别人挂了……

**Comment by afc163** [comment]
@zombieJ 这个漏掉了

**Comment by zombieJ** [comment]
汗，那复制一份吧。在 antd 里做个 warning……

**Pull request closed without merging**
