### PR TITLE
ci: update ci version

### PR DESCRIPTION
**Pull request by wzhudev**

### CODE REVIEW

**Comment by jornare** [comment]
any idea why it is failing?

**Comment by wzhudev** [comment]
@vagusX Please check CI. There is something wrong with icons-svg. Compiling fails.

**Comment by jornare** [comment]
Try updating TypeScript to v4 or v5.

**Comment by vagusX** [comment]
> @vagusX Please check CI. There is something wrong with icons-svg. Compiling fails.

ok

**Comment by vagusX** [comment]
> @vagusX Please check CI. There is something wrong with icons-svg. Compiling fails.

Fixed https://github.com/ant-design/ant-design-icons/pull/569

**Pull request closed without merging**
