### PR TITLE
feature: sync with official icon library

### PR DESCRIPTION
**Pull request by HeskeyBaozi**
此 `pr` 只改动 `@ant-design/icons-svg`，包括以下更改：

- 和设计师发布的 [iconfont官方图标库](https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=9402) 保持同步，新增了50个单色图标（Filled风格4个，Outlined风格46个）
- 为 **9**个 图标添加别名，原则为更加贴合语义和图标命名规范。**注意：这一项需要审核**
- 删除了 **5**个 图标，删除原因为两种风格图标一模一样所以通常是删去其中一种风格（如Filled），或者是单纯图标名称拼写错误。**注意：这一项需要审核**

### CODE REVIEW

**Comment by HeskeyBaozi** [comment]
# Change Log

[Ofiicial icons library | 官方 iconfont 图标库](https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=9402)

## New Icons

These icons will be added in the next version.

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| aim | - | aim | - |
| appstore-add | - | appstore-add | - |
| audio-muted | - | audio-muted | - |
| borderless-table | - | borderless-table | - |
| clear | - | clear | - |
| comment | - | comment | - |
| compress | - | compress | - |
| console-sql | - | console-sql | - |
| delete-column | - | delete-column | - |
| delete-row | - | delete-row | - |
| delivered-procedure | - | delivered-procedure | - |
| expand | - | expand | - |
| field-binary | - | field-binary | - |
| field-number | - | field-number | - |
| field-string | - | field-string | - |
| field-time | - | field-time | - |
| file-gif | - | file-gif | - |
| folder-view | - | folder-view | - |
| format-painter | format-painter-f | format-painter-o | - |
| function | - | function | - |
| fund-projection-screen | - | fund-projection-screen | - |
| fund-view | - | fund-view | - |
| gif | - | gif | - |
| group | - | group | - |
| insert-row-above | - | insert-row-above | - |
| insert-row-below | - | insert-row-below | - |
| insert-row-left | - | insert-row-left | - |
| insert-row-right | - | insert-row-right | - |
| mac-command | mac-command-f | mac-command-o | - |
| merge-cells | - | merge-cells | - |
| node-collapse | - | node-collapse | - |
| node-expand | - | node-expand | - |
| node-index | - | node-index | - |
| one-to-one | - | one-to-one | - |
| partition | - | partition | - |
| robot |  robot-f | - | - |
| rotate-left | - | rotate-left | - |
| rotate-right | - | rotate-right | - |
| send | - | send | - |
| sisternode | - | sisternode | - |
| signal | signal-f | - | - |
| split-cells | - | split-cells | - |
| subnode | - | subnode | - |
| translation | - | translation | - |
| ungroup | - | ungroup | - |
| user-switch | - | user-switch | - |
| verified | - | verified | - |
| video-camera-add | - | video-camera-add | - |
| whats-app | - | whats-app | - |



## New alias Icons

These icons will be added new alias in the next version.

### `arrows-alt` => `expand-alt`

`arrows-alt` 这个名字不删除，`expand-alt` 为别名

| Icon | Name (old) | Name (new) | Theme |
|:----:|:----:|:----:|:----:|
| expand-alt | arrows-alt  |  **expand**-alt |  Outlined |

### `dingding` => `dingtalk`

`dingding` 这个名字不删除，`dingtalk` 为别名

| Icon | Name (old) | Name (new) | Theme |
|:----:|:----:|:----:|:----:|
| dingtalk | dingding  |  ding**talk** |  Outlined |

### `ci` => `ci-circle`

```diff
  ci-circle-filled
  ci-outlined
  ci-twotone
+ ci-circle-outlined
+ ci-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| ci-circle | ci-circle-f | - | - |
| ci | - | ci-circle-o | ci-circle-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| ci-circle | ci-circle-f | ci-circle-o | ci-circle-tt |
| ci | - | ci-circle-o | ci-circle-tt |

### `copyright` => `copyright-circle`

```diff
  copyright-circle-filled
  copyright-outlined
  copyright-twotone
+ copyright-circle-outlined
+ copyright-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| copyright-circle | copyright-circle-f | - | - |
| copyright | - | copyright-circle-o | copyright-circle-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| copyright-circle | copyright-circle-f | copyright-circle-o | copyright-circle-tt |
| copyright | - | copyright-circle-o | copyright-circle-tt |

### `dollar` => `dollar-circle`

```diff
  dollar-circle-filled
  dollar-outlined
  dollar-twotone
+ dollar-circle-outlined
+ dollar-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| dollar-circle | dollar-circle-f | - | - |
| dollar | - | dollar-circle-o | dollar-circle-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| dollar-circle | dollar-circle-f | dollar-circle-o | dollar-circle-tt |
| dollar | - | dollar-circle-o | dollar-circle-tt |

### `euro` => `euro-circle`

```diff
  euro-circle-filled
  euro-outlined
  euro-twotone
+ euro-circle-outlined
+ euro-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| euro-circle | euro-circle-f | - | - |
| euro | - | euro-circle-o | euro-circle-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| euro-circle | euro-circle-f | euro-circle-o | euro-circle-tt |
| euro | - | euro-circle-o | euro-circle-tt |

### `golden` => `gold`

```diff
  golden-filled
+ gold-filled
  gold-outlined
  gold-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| golden | gold-f | - | - |
| gold | - | gold-o | gold-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| golden | gold-f | - | - |
| gold | gold-f | gold-o | gold-tt |

### `pound` => `pound-circle`

```diff
  pound-circle-filled
  pound-outlined
+ pound-circle-outlined
  pound-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| pound-circle | pound-circle-f | - | pound-circle-tt |
| pound | - | pound-circle-o | - |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| pound-circle | pound-circle-f | pound-circle-o | pound-circle-tt |
| pound | - | pound-circle-o | - |

### `trademark` => `trademark-circle`

```diff
  trademark-circle-filled
  trademark-outlined
+ trademark-circle-outlined
  trademark-circle-twotone
```

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| trademark-circle | trademark-circle-f | - | trademark-circle-tt |
| trademark | - | trademark-circle-o | - |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| trademark-circle | trademark-circle-f | trademark-circle-o | trademark-circle-tt |
| trademark | - | trademark-circle-o | - |








## Removed Icons

These icons will be removed in the next version.

| Name | Icon | Theme | Reason |
|:----:|:----:|:----:|:----:|
| ca**n**lendar | calendar | TwoTone | misspelling. use `calendar` instead. |
| interation | interaction-f interaction-o interaction-tt  | Filled/Outlined/TwoTone | misspelling. use `interaction` instead. |
| colum-height | column-height | Outlined | misspelling. use `column-height` instead. |

**Comment by vagusX** [comment]
上面这些 changes 需要在 @ant-design/compatible 中做兼容
* remove 的部分需要在 @ant-design/compatible 中将其 rename 掉

**Comment by zombieJ** [comment]
不用删除，可以先占位。等有对应的图标后补上就行了。免得用户用了升级 break 掉。

**Comment by HeskeyBaozi** [comment]
> 不用删除，可以先占位。等有对应的图标后补上就行了。免得用户用了升级 break 掉。

好的。也就是说现在是为了防止用户宕掉稳一点，不减少图标的数量。即使一些图标存在一些拼写错误（例如上面的 canlendar 和 interation ），也是可以容忍的。同时重命名的图标，采用 alias 的方式，多一个别名，原来的名字依然保留。

**例如 `ci` 和 `ci-circle`**

#### ❌ Before 

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| ci-circle | ci-circle-f | - | - |
| ci | - | ci-circle-o | ci-circle-tt |

#### ✔️ Now

| Name | Filled | Outlined | TwoTone |
|:----:|:----:|:----:|:----:|
| ci-circle | ci-circle-f | ci-circle-o | ci-circle-tt |
| ci | - | ci-circle-o | ci-circle-tt |

**Comment by vagusX** [comment]
> 好的。也就是说现在是为了防止用户宕掉稳一点，不减少图标的数量。即使一些图标存在一些拼写错误（例如上面的 canlendar 和 interation ），也是可以容忍的。同时重命名的图标，采用 alias 的方式，多一个别名，原来的名字依然保留。

拼写错误的我感觉 svg 这个库可以干掉，因为在 compatible 里面兼容，新的 icons-react 是可以直接废弃掉这部分图标的吧 @zombieJ @HeskeyBaozi 

刚才按错了快捷键把 pr close 掉了不好意思

**Comment by zombieJ** [comment]
拼写错误 codemod 可以覆盖得到不？ @vagusX 
如果可以，那只用保留 Filled Outlined 丢失的情况，拼写错误可以干掉。

**Comment by HeskeyBaozi** [comment]
> 拼写错误 codemod 可以覆盖得到不？ @vagusX
> 如果可以，那只用保留 Filled Outlined 丢失的情况，拼写错误可以干掉。

commit 已提交。现在 changelog 中不再以“重命名图标”这样不明确的字眼，修改为为部分图标添加别名，意在体现原来的图标不会被删除，使用者可以放心兼容。

现在唯一注意的是只有 `canlender` 和 三种风格的 `interation` 图标由于拼写错误原因已经被删除。需要使用者注意。

**Comment by vagusX** [comment]
<del>codemod 也是调用了compatible 的查找规则去生成新的v4图标名，所以对于 calendar和interaction这两个图标的兼容只需要在 compatible 包里面做一次即可，对应地，codemod也会生效 @zombieJ</del>

维持之前结论，增加别名即可

**Comment by vagusX** [comment]
貌似还有一个 `colum-height` 这个有删除掉嘛 @HeskeyBaozi 

```js
  switch (type) {
    case 'cross':
      newType = 'close';
      break;
    // https://github.com/ant-design/ant-design/issues/13007
    case 'interation':
      newType = 'interaction';
      break;
    // https://github.com/ant-design/ant-design/issues/16810
    case 'canlendar':
      newType = 'calendar';
      break;
    // https://github.com/ant-design/ant-design/issues/17448
    case 'colum-height':
      newType = 'column-height';
      break;
    default:
  }
```

**Comment by HeskeyBaozi** [comment]
@vagusX 

> "华生你发现了盲点"

已经移除
```diff
- colum-height-outlined
  column-height-outlined
  column-width-outlined
```

**Comment by wzhudev** [comment]
我试着总结一下框架适配包要做的事情：

1. 兼容 icon type 名称的改变
2. 对于 removed 和 renamed 的图标做警告，替换成新图标名称

@HeskeyBaozi 是这样吗？

我觉得适配层能兼容的东西没必要在底包里留着。

**Comment by HeskeyBaozi** [comment]
@wendellhu95 
> 我试着总结一下框架适配包要做的事情：
> 
> 1. 兼容 icon type 名称的改变
> 2. 对于 removed 和 renamed 的图标做警告，替换成新图标名称
> 
> @HeskeyBaozi 是这样吗？
> 
> 我觉得适配层能兼容的东西没必要在底包里留着。

实际上显示警告只用对删除的 5 个拼写错误图标就行了。
事实上我对着文档检查了一下：这5个错误图标本身就没有在 [`React Antd` 官方文档](https://ant.design/components/icon-cn/)里显示（也包括 `NG-ZORRO` 中的图标文档），所以正常情况下，对着文档正常使用的用户影响应该几乎为0。

不过，出于对开源库的原则性思考，你说的给个 `warning` 提示很对，对于开发者体验有很大改善。

感谢您对图标社区的付出（比心）。

**Pull request merged**
