### PR TITLE
feat(module:icons-angular): add icons-angular

### PR DESCRIPTION
**Pull request by wzhudev**
Ref #3.
fill
outline
twotone

### CODE REVIEW

**Comment by wzhudev** [comment]
I'll add tests later. Working on ng-zorro-antd now...

**Comment by HeskeyBaozi** [comment]
我看到构建图标的代码直接迁移到了 `@ant-design/icons-angular` 内部。
这样代码两边都要维护成本是否过高？

**Comment by wzhudev** [comment]
现在底包生成的东西太 React 了, 对 Angular 来说没有用处,  除非用策略模式改写一下生成脚本, 每个平台封装一组生成文件函数.

而且我们这边要做一个动态加载, 需要处理过后的 .svg 文件, 所以就单独搞了一套.

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design-icons#render-helpers
`@ant-design/icons@^1.1.12`

**Comment by wzhudev** [comment]
@HeskeyBaozi Hi. I tried to use the new API this morning. Though icons could be rendered when static importing is used (like `@ant-design/icons-react` does), I find out that dynamic loading cannot be implemented because all resources I can use is `.ts` files. I could not figure out how to dynamically load TypeScript modules in browsers. In another word, I need `.svg` files and I don't know how to generate them without modifying the `generateIcon` script.

**Comment by HeskeyBaozi** [comment]
https://unpkg.com/@ant-design/icons@1.1.13/inline-svg/
Make sure that place colors when using two-tone icons

**Comment by wzhudev** [comment]
@HeskeyBaozi I've updated my code. Please review again.

**Comment by HeskeyBaozi** [comment]
We now use lerna, the work directory is now migrated from `/` to `/packages/icons`

commands:
`yarn run generate` => `yarn run icons:generate`
`yarn run build` => `yarn run icons:build`

**Comment by wzhudev** [comment]
@HeskeyBaozi Adapted lerna to icons-angular already.

**Pull request merged**
