### PR TITLE
reload-time => history

### LINKED ISSUE #15850: History icon
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, could you add an icon for "History"  Maybe something that looks like a clock with an arrow around it indicating going back in time?

### What does the proposed API look like?
Maybe something like this icon https://www.iconfinder.com/icons/352426/history_icon

### PR DESCRIPTION
**Pull request by afc163**
close ant-design/ant-design#15850

https://github.com/ant-design/ant-design-icons/issues/26

### CODE REVIEW

**Comment by zombieJ** [comment]
@wendzhue , I see you add `Beak Change` label. Is that safe to merge this?

**Comment by afc163** [comment]
I don't see https://ng.ant.design/components/icon/zh using `reload-time` and `mr` icons.

**Comment by wzhudev** [comment]
@zombieJ I am afraid merging this PR would introduce a breaking change if we don't get down to some adapting works - which is quite muddy.

**Comment by zombieJ** [comment]
Agree. Maybe we can support alias?

ref: #32

**Comment by afc163** [comment]
发一个 2.0.0 好了，上层框架去抹平 breaks

**Comment by wzhudev** [comment]
有一个 map 吗？

**Comment by afc163** [comment]
- `reload-time` => `history`
- `interation` => `interaction` #32
- `mr` => `pull-request`

**Comment by rsmolkin** [comment]
Should these new icons be shown here: https://ant.design/components/icon/

**Comment by zombieJ** [comment]
> Should these new icons be shown here: https://ant.design/components/icon/

We released `2.0` which will update in next minor version of `antd`: https://github.com/ant-design/ant-design/pull/15874

**Pull request merged**
